name = "Parser"
defaultTargets = ["Parser"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.9.0"

[[require]]
name = "UnicodeBasic"
git = "https://github.com/fgdorais/lean4-unicode-basic"
rev = "stable"

[[lean_lib]]
name = "Parser"
